### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by ozi2277** [leodesigner/espNowFloodingMeshLibrary2#5]
Hi! Your library is amazing!! I admire you how much time you put into modifying this library. I've been using it for a while now and I have a question. Will there ever be an upgrade to be able to use the library for esp32 version 2.0 or higher ??

**Comment by leodesigner** [comment]
Thank you @ozi2277  :)
Do you mean Arduino framework version for ESP32?
I had no chance to test it, what kind of compile errors you are getting ?

**Comment by ArminPP** [comment]
Hello ozi2277,
I use this library in PlatformIO with version >2.0, I think.
And it works like a charm, thanks again @loedesigner :-)

PIO says after compiling:
 - framework-arduinoespressif32 @ 3.20009.0 (2.0.9) 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5

So I think 2.0.9 is the Version ?

Five months ago I wrote a little test program for this library: https://github.com/ArminPP/M5Atom_ESP-MESH_Test
It is written for M5Stack Atom, but should also work also with a plain ESP32.

**Comment by ozi2277** [comment]
> Thank you @ozi2277 :) Do you mean Arduino framework version for ESP32? I had no chance to test it, what kind of compile errors you are getting ?

That's about the arduino ide and more specifically I'm using Visual Studio with the visualmicro "arduino" add-on. This morning my hard drive crashed and I had to reinstall everything but I managed to solve the problem of incorrect compiling of the program. The error was with your espNowFloodingMeshLibrary2 library, specifically wifi802_11.cpp, line 136:
esp_wifi_80211_tx(ESP_IF_WIFI_STA, buf, sizeof(raw_HEADER) + len + 2, true);
I don't remember the exact message but it was "cannot convert esp_interface to user_interface" but something similar.. The problem was changing enum names in ESP32 for libraries from 2.0.0 and newer.
 It was enough to replace the argument name of the "ESP_IF_WIFI_STA" function with "WIFI_IF_STA" -> esp_wifi_80211_tx(WIFI_IF_STA, buf, sizeof(raw_HEADER) + len + 2, true);
After this change everything works without problems, I tested for the latest version for arduino IDE ESP32 lib v 2.0.10

I'm basically an amateur programmer and sorry for my English.

**Comment by leodesigner** [comment]
I guess we can close the issue now.
Thanks.

**Comment by harshadvekariya** [comment]
@ozi2277 Did you get it working? I am facing some issue with ESP32. 

I am using https://github.com/ArminPP/M5Atom_ESP-MESH_Test example by @ArminPP (Thanks for sharing :))

problems:
1) while using ESP32 as master and ESP32 as slave, Esp32 is able to send the message but is not receiving message. I tried changing `time_t` to `uint64_t` as suggested here but no luck https://github.com/leodesigner/espNowFloodingMeshLibrary2/issues/7. When I use ESP32 master and ESP8266 slave, same behaviour observerd. ESP8266 shows send and recieved in the terminal, ESP32 only shows send. 

2) While using ESP8266 master and ESP8266 slave I get send and recieve message on both devices Serial monitor, but another problem of time sync as mentioned here https://github.com/ArminPP/M5Atom_ESP-MESH_Test/issues/1
